<?php
session_start();
$_SESSION["domain"]='geomatika';
require("globprefs.php");
require_once 'extras/phplayersmenu/lib/PHPLIB.php';
require_once 'extras/phplayersmenu/lib/layersmenu-common.inc.php';
require_once 'extras/phplayersmenu/lib/layersmenu.inc.php';

// on récupere des éléments sur le domaine
$query="select * from defappli where contrib='bureau'";
$result=pg_query($link,$query);
$line=pg_fetch_assoc($result);
$_SESSION["urlsortie"]=$line["url"];

//print_r($line);


if(isset($_FILES['datafile']))
{
  $uploadfile=TMP_DIR.basename ( $_FILES [ 'datafile' ][ 'name' ]);
    //echo $uploadfile."\r\n".$_FILES [ 'datafile' ][ 'tmp_name' ];
  move_uploaded_file ( $_FILES [ 'datafile' ][ 'tmp_name' ], $uploadfile );
  $oMS=new MapSession_RW;
  $oMS->readMapFile($uploadfile);
	  //print_r($http_form_vars);
	  //print_r($_FILES);
	  //echo "burp ".basename ( $_FILES [ 'datafile' ][ 'name' ]);
}

//print_r($_SESSION);

?>
<html>
<head>
<title>IsiGéo mapedit</title>
<style title="default" type="text/css" media="screen">
<?php
echo "@import url(css/geomatika/menu.css);";
echo "@import url(css/onglets.css);";
echo "@import url(css/mapfile.css);";


?>
</style>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/javascript" src="extras/phplayersmenu/libjs/layersmenu-browser_detection.js"></script>
<script language="JavaScript" type="text/javascript" src="extras/phplayersmenu/libjs/layersmenu-library.js"></script>
<script language="JavaScript" type="text/javascript" src="extras/phplayersmenu/libjs/layersmenu.js"></script>

<link rel="stylesheet" type="text/css" href="css/NiftyLayout.css">
<link rel="stylesheet" type="text/css" href="css/geomatika/bureau.css">
<link rel="stylesheet" type="text/css" href="extras/colorpicker/colorpicker.css">

<script type="text/javascript" src="extras/niftycube/niftycube.js"></script>

<script type="text/javascript" src="extras/scriptaculous/lib/prototype.js"></script>
<script type="text/javascript" src="extras/scriptaculous/src/effects.js"></script>
<script type="text/javascript" src="extras/scriptaculous/src/dragdrop.js"></script>

<script language="JavaScript" type="text/javascript" src="javascript/DialogWindow.js"></script>
<script language="JavaScript" type="text/javascript" src="javascript/Listener.js"></script>


<script language="JavaScript" type="text/javascript" src="javascript/MapFile.js"></script>
<script language="JavaScript" type="text/javascript" src="javascript/mapedit.js"></script>

<script type="text/javascript" src="extras/scriptaculous/src/builder.js"></script>
<script type="text/javascript" src="extras/scriptaculous/src/slider.js"></script>
<script type="text/javascript" src="extras/colorpicker/yahoo.color.js"></script>
<script type="text/javascript" src="extras/colorpicker/colorPicker.js"></script>

<script language="JavaScript" type="text/javascript" src="javascript/debug.js"></script>
<script>
var viewer=null;
function exit()
{
	document.location.href="http://<?php echo $_SESSION["urlsortie"]; ?>/bureau.phtml?domain=<?php echo $_SESSION["domain"]; ?>";
}
function openViewer(){
  //alert(mapFile.MFName+"  "+null);
  
	alert(ongletActive);
	if(mapFile.state=="MODIFY"){
    if(ongletActive=="affiche_layer" || ongletActive=="layers"){
      alert(currentLayer);
			mapFile.modifyLayer(mapFile.getLayer(currentLayer));
      mapFile.initState();
    }else{
      mapFile.modifyMF();
      mapFile.initState();
    }
  }
  <?php
    echo 'urlViewer="'.VIEWER.'";';
    echo 'repmap="'.$_SESSION["domain"].'";';
  ?>
 // alert(urlViewer);
  var name=mapFile.tmpname.split(".")[0];
  if(viewer==null){
   //var extent=mapFile.data.extent.minx+","+mapFile.data.extent.miny+","+mapFile.data.extent.maxx+","+mapFile.data.extent.maxy;
    var extent=null;
		viewer=window.open(urlViewer+"?contrib=prototype&geoset="+name+"&repmap="+repmap+"&extent="+extent,"viewer");
  }else{
    if(viewer.closed){
      viewer=window.open(urlViewer+"?contrib=prototype&geoset="+name+"&repmap="+repmap+"&extent="+extent,"viewer");
    }else{
      viewer.location.href=urlViewer+"?contrib=prototype&geoset="+name+"&repmap="+repmap+"&extent="+extent;
    }
  }
}
</script>
</head>
<body onload="javascript:initnifty();">
<div id="bandeau"></div>
<div id="header">
<div id="ongletsprinc">
<ul id="nav">
<li id="home" class="activelink"><a href="#">Mapeditor</a></li>
<!--li id="who"><a href="http://forum.geomatika.fr" target="_blank" title="Forum des utilisateurs">Forum</a></li-->
<li id="prod"><a href="#">A propos</a></li>
<!--li id="serv"><a href="#">Services</a></li-->
<!--li id="cont"><a href="#">Contact us</a></li-->
</ul>
</div>
</div>
<div id="container">
	<div id="bandeau1">
     	<table class="fondbandeau1" style="width:100%;padding:0px;margin:0px;"><tr>
			 <td style="text-align:center;width:24px;">

 <a href="javascript:openwin();" ><img src="images/home.png" width="22" height="22" border="0"></a>
 </td>

 <td style="text-align:right;">
 <a href="javascript:exit();" ><img src="images/exit.png" width="22" height="22" border="0" class="png"></a>
 </td>
 <td style="text-align:right;width:150px;" class="corpsblack">
	<?php
	echo date("D m M Y");
	echo "<br>".$_SESSION["QUI_U"];
	?>
		</td></tr></table>
	</div>    <!--  bandeau1 -->

  <div style="background-color:#DFDFDF;padding-left:10px;border-bottom:1px solid #656565;border-top:1px dashed #656565;">
   <?php
  $mid = new LayersMenu(6, 7, 2, 1);
  $mid->setDirrootCommon("extras/phplayersmenu/");
  $mid->setMenuStructureFile('menumapedit.txt');
  $mid->setTpldir("extras/phplayersmenu/templates/");
  $mid->setImgdir("extras/phplayersmenu/menuimages/");
  $mid->setImgwww("extras/phplayersmenu/menuimages/");
  $mid->setIconsize(16, 16);
  $mid->parseStructureForMenu('menu');
  $mid->newHorizontalMenu('menu');
  $mid->printHeader();
  $mid->printMenu('menu');
  $mid->printFooter();
  ?>
   </div>
	<div id="content">
	<?php
	//print_r($_SESSION);
	?>
<br>


  <div id="global">
  <img id="viewerimg" onclick="openViewer();" src="images/viewer.png" title="Visualiser la carte">

  <div id="headermf">
	<div id="onglets">
   <ul id="navmf">
    <li id="parametres" class="activelink"><a href="#">Paramètres</a></li>
    <li id="layers"><a href="javascript:flipOnglet('layers')">Layers</a></li>
    <li id="symbols" style="display:none;"><a href="javascript:flipOnglet('symbols')">Symboles</a></li>
    <li id="affiche_layer" style="display:none;"><a href="javascript:flipOnglet('affiche_layer')"><span id="affiche_layer_libelle"></span></a></li>
   </ul>
  </div>
  </div>    <!--headermf-->
  <div id="ficheonglet">

    <div id="mapfile" style="margin:0px;padding:10px;background-color:white;">
    </div>
  </div>  <!--ficheonglet-->

  </div>    <!--global-->


	</div>    <!--content-->

<br>
</div>  <!--container-->



<div style="position:absolute;border:1px solid black;background-color:white;display:none;width:337px;height:375px;" id="maincolor" class="corpsblack" imgLoc="./"></div>
<script language="JavaScript" src="cpick.js"></script>
</div>
</body>
</html>