
<html>
<head>
<title>Nifty Corners Layout</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" type="text/css" href="css/NiftyLayout.css">
<link rel="stylesheet" type="text/css" href="css/geomatika/bureau.css">

<script type="text/javascript" src="extras/niftycube/niftycube.js"></script>
<script type="text/javascript" src="javascript/niftyLayout.js"></script>
</head>
<body>

<div id="bandeau"></div>

<div id="header">

<div id="menu">
<ul id="nav">
<li id="home" class="activelink"><a href="#">Bureau</a></li>
<li id="who"><a href="http://forum.geomatika.fr" target="_blank" title="Forum des utilisateurs">Forum</a></li>
<li id="prod"><a href="#">A propos</a></li>
<li id="serv"><a href="#">Services</a></li>
<!--li id="cont"><a href="#">Contact us</a></li-->
</ul>
</div>
</div>
<div id="container">
	<div id="bandeau1">
     	<table class="fondbandeau1" style="width:770px;padding:0px;margin:0px;"><tr>
			 <td style="text-align:center;width:24px;">
 <a href="javascript:openwin();" ><img src="images/kopete005.png" width="22" height="22" border="0"></a>
 </td>
 <td style="text-align:center;width:24px;">
 <a href="javascript:openwin('identity');" ><img src="images/home.png" width="24" height="24" border="0" class="png"></a>
 </td>
 <td style="text-align:right;">
 <a href="javascript:openwin('identity');" ><img src="images/exit.png" width="22" height="22" border="0" class="png"></a>
 </td>
 <td style="text-align:center;width:10px;">-</td>
 <td style="text-align:right;width:90px;" class="corpsblack">
	<?php
	echo date("D m M Y");
	echo "<br>".$_SESSION["QUI_U"];
	?>
		</td></tr></table>
	</div>    <!--  bandeau1 -->
<br>

	<div id="content">

		<div class="date"><?php echo date("D");?> <span><?php echo date("m");?></span> <?php echo date("Y");?></div>

<ul id="intro">
<li id="mission"><h3>Our Mission</h3><p>Oeoua aau ieiu a eoiu eo eoi ee ieeao uaio uoaua u iii.</p></li>
<li id="services"><h3>Our Services</h3><p>Euiuee iau oo ouo   uei e ae oiuueo.</p></li>
</ul>

<h2>Nifty Corners Layout: ready for colors</h2>

<p>Aoi aoauoo e oei ii oeu uioauaa ouoeuii aui oeeuoo oeoii oaooii eie aioe ae ueeaoi ieo aio eiaoeeo oe iia eeo oueu oaaiuui iiiiu auoiie ee u aeuei uio ue oouo eeai aoo i ieuaieii.</p>
	</div>


	<div id="side" class="corpsblack">
<h3>Actualit&eacute;s</h3>
<p>Oi ieueea oeee uuio ouuo u oiu iao aaiou iaioue eououa iia uaeioo uei eo iiouu aoe ouu a iieuau i euaouu aua eiooa uiu aeoeo oe aoeo oi oo oiieu uio auie.</p>
	</div>

<br> <br><br><br><br><br>
<br> <br><br><br><br><br>
<br> <br><br><br><br><br>
</div>

</body>
</html>